name: Prepare project

description: "Clone repo, get configs for project"

inputs:
  gcp-key-base64:
    required: true
    description: "Google Credentials Secret for performing actions base64 format"

runs:
  using: "composite"

  steps:
    - name: "Checkout repository"
      uses: "actions/checkout@v4"

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ inputs.gcp-key-base64 }}'
