name: Prepare project

description: "Clone repo, get configs for project"

inputs:
  gcp-sa-key:
    required: true
    description: "Google Credentials Secret for performing actions"
  gcp-project-id:
    required: true
    description: "Google Project ID"
  gcp-plain-secret-name:
    required: true
    description: "Google Secret Manager secret name with Plain config"
  gcp-base64-secret-name:
    required: true
    description: "Google Secret Manager secret name with base64 config"
  gcp-app-engine-config-name:
    required: false
    description: "Deploy project to Google AppEngine with config. This input trigger step: appengine-deploy"
  env-variables-config-file:
    required: false
    default: ".env"
    description: "Use this var for your secret storing"
  env-variables-base64-config-file:
    required: false
    description: "Use this var to dump base64 secret to separate file"
  db-instance:
    required: false
    description: "Database instance to connect with Google Cloud SQL Proxy. This input trigger step: setup-cloudsql-proxy"
  custom-shell-command:
    required: false
    description: "Run custom shell command after prepare. This input trigger step : custom-shell-command"

runs:
  using: "composite"

  steps:
    - name: "Checkout repository"
      uses: "actions/checkout@v3"

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ inputs.gcp-sa-key }}'

    - id: 'secrets-plain'
      if: ${{ inputs.gcp-plain-secret-name != 0 }}
      uses: 'google-github-actions/get-secretmanager-secrets@v0'
      with:
        secrets: |-
          body:projects/${{ inputs.gcp-project-id }}/secrets/${{ inputs.gcp-plain-secret-name }}

    - id: 'secrets-base64'
      if: ${{ inputs.gcp-base64-secret-name != 0 }}
      uses: 'google-github-actions/get-secretmanager-secrets@v0'
      with:
        secrets: |-
          base64body:project/${{ inputs.gcp-project-id }}/secrets/${{ inputs.gcp-base64-secret-name }}

    # Plain secret dump
    - name: Get secret from Google Secrets to env-variables-config-file
      if: ${{ inputs.gcp-plain-secret-name != 0 }}
      run: echo "${{ steps.secrets-plain.outputs.body }}" >> ${{ inputs.env-variables-config-file }}
      shell: "bash"


    # Dump base64 secret in separate file
    
    - name: Get base64-encoded from Google Secrets to separate file (env-variables-base64-config-file)
      if: ${{ inputs.gcp-base64-secret-name != 0  && inputs.env-variables-base64-config-file != 0 }}
      run : echo "${{ steps.secrets-base64.outputs.base64body }}" | base64 -d >> ${{ inputs.env-variables-base64-config-file }}
      shell: "bash"

    # Dump base64 secret to .env file or app-dev.yaml

    - name: Get base64-encoded from Google Secrets to env-variables-config-file 
      if: ${{ inputs.gcp-base64-secret-name != 0  && inputs.env-variables-base64-config-file == 0 }}
      run : echo "${{ steps.secrets-base64.outputs.base64body }}" | base64 -d >> ${{ inputs.env-variables-config-file }}
      shell: "bash"

    - name: Setup Google Cloud SQL Proxy
      id: 'setup-cloudsql-proxy'
      if: ${{ inputs.db-instance != 0 }}
      uses: mattes/gce-cloudsql-proxy-action@v1
      with:
        creds: "${{ inputs.gcp-sa-key }}"
        instance: "${{ inputs.db-instance }}"

    - name: "Custom bash shell command"
      id: 'custom-shell-command'
      if: ${{ inputs.custom-shell-command != 0 }}
      run: "${{ inputs.custom-shell-command }}"
      shell: "bash"    

    - name: 'Deploy to App Engine'
      id: 'appengine-deploy'
      if: ${{ inputs.gcp-app-engine-config-name != 0 }}
      uses: 'google-github-actions/deploy-appengine@v0'
      with:
        deliverables: "${{ inputs.gcp-app-engine-config-name }}"
        promote: true
