name: Prepare project

description: "Clone repo, get configs for project"

inputs:
  gcp-sa-key:
    required: true
    description: "Google Credentials Secret for performing actions"
  gcp-project-id:
    required: true
    description: "Google Project ID"
  gcp-plain-secret-name:
    required: true
    description: "Google Secret Manager secret name with Plain config"
  gcp-base64-secret-name:
    required: true
    description: "Google Secret Manager secret name with base64 config"

runs:
  using: "composite"

  steps:
    - name: "Checkout repository"
      uses: "actions/checkout@v3"

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ inputs.gcp-sa-key }}'

    - id: 'secrets'
      uses: 'google-github-actions/get-secretmanager-secrets@v0'
      with:
        secrets: |-
          body:projects/${{ inputs.gcp-project-id }}/secrets/${{ inputs.gcp-secret-name }}
          base64body:project/${{ inputs.gcp-project-id }}/secrets/${{ inputs.gcp-secret-name }}

    - name: Delete .env file if exists
      run: "rm -fr .env"
      shell: "bash"

    - name: Get secret from Google Secrets
      run: echo "${{ steps.secrets.outputs.body }}" > .env
      shell: "bash"

    - name: Get base64-encoded from Google Secrets
      run : echo "${{ steps.secrets.outputs.base64body }}" | base64 -d >> .env
      shell: "bash"
